# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{netflix4r}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["rossnelson"]
  s.date = %q{2011-08-07}
  s.description = %q{a ruby client for the NetFlix API}
  s.email = %q{axcess1@me.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "credentials.yml",
    "lib/flix4r.rb",
    "lib/net_flix.rb",
    "lib/net_flix/.DS_Store",
    "lib/net_flix/api/.DS_Store",
    "lib/net_flix/api/catalog/.DS_Store",
    "lib/net_flix/api/catalog/titles.rb",
    "lib/net_flix/authenticator.rb",
    "lib/net_flix/builders/.DS_Store",
    "lib/net_flix/builders/actor_builder.rb",
    "lib/net_flix/builders/format_builder.rb",
    "lib/net_flix/builders/title_builder.rb",
    "lib/net_flix/credentials.rb",
    "lib/net_flix/request.rb",
    "lib/net_flix/title.rb",
    "lib/valuable.rb",
    "log/netflix.log",
    "netflix4r.gemspec",
    "rakefile.rb",
    "samples/.DS_Store",
    "samples/actors.rb",
    "samples/download_full_catalog.rb",
    "samples/formats.rb",
    "samples/search.rb",
    "test/actor_builder_test.rb",
    "test/authenticator_test.rb",
    "test/credentials_test.rb",
    "test/format_builder_test.rb",
    "test/helper.rb",
    "test/request_test.rb",
    "test/test.rb",
    "test/test_flix4r.rb",
    "test/test_helpers.rb",
    "test/tests.rb",
    "test/title_builder_test.rb",
    "test/title_test.rb"
  ]
  s.homepage = %q{http://github.com/rossnelson/flix4r}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{copy of http://code.google.com/p/flix4r/}
  s.test_files = [
    "test/actor_builder_test.rb",
    "test/authenticator_test.rb",
    "test/credentials_test.rb",
    "test/format_builder_test.rb",
    "test/helper.rb",
    "test/request_test.rb",
    "test/test.rb",
    "test/test_flix4r.rb",
    "test/test_helpers.rb",
    "test/tests.rb",
    "test/title_builder_test.rb",
    "test/title_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-hmac>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-hmac>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<ruby-hmac>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<ruby-hmac>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<ruby-hmac>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<ruby-hmac>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

